---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/secure-backends: "true"
  name: pttg-fs-calc-ui
spec:
  rules:
  - host: fs.calc.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    http:
      paths:
      - backend:
          serviceName: pttg-fs-calc-ui
          servicePort: 443
        path: /
  tls:
  - hosts:
    - fs.calc.{{.DNS_PREFIX}}pttg.homeoffice.gov.uk
    secretName: letsencrypt-tls