---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: pttg-fs-calc-ui
  name: pttg-fs-calc-ui
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
  selector:
    name: pttg-fs-calc-ui
